apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: patrickkingpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: patrickkingpipelinesjavascriptdocker 
    spec:
      containers:
        - name: patrickkingpipelinesjavascriptdocker 
          image: pk2containerregistry.azurecr.io/patrickkingpipelinesjavascriptdocker
          ports:
          - containerPort: 8080